### ISSUE TITLE
请问这个怎么和官方的npm库直接结合啊？是直接引入官方的scr 在引入你的吗？

### ISSUE THREAD

**Issue by zcx992132258** [yuzd/ace_clickhouse#1]

**Comment by yuzd** [comment]
就2个js 
你看下我源码怎么弄的，再看怎么配合你的项目

**Comment by yuzd** [comment]
目前是都放在了ace_clickhouse.js里面 比如ace之类的
如果 引入了官方的 那就得去掉

**Comment by zcx992132258** [comment]
我是这样的
![image](https://github.com/yuzd/ace_clickhouse/assets/54138798/0c2bfaf3-b2f6-4f06-b9a3-a2f64e2fad53)
然后下面是把你的clickhouse的放下面
![image](https://github.com/yuzd/ace_clickhouse/assets/54138798/4b03c298-e810-4296-b15f-65905c6ddf5d)
![image](https://github.com/yuzd/ace_clickhouse/assets/54138798/7dd33144-8f04-4a92-9a83-8908fa511ed6)
报错这个我 应该怎么处理啊
![image](https://github.com/yuzd/ace_clickhouse/assets/54138798/7e712703-ff14-4a9d-852a-a96497d672c0)

**Comment by yuzd** [comment]
![image](https://github.com/yuzd/ace_clickhouse/assets/16083659/d77b5d0b-6bc9-4961-b944-b9551083ecb3)

你拉下工程，看下这个能跑起来吗

**Comment by zcx992132258** [comment]
是可以跑起来的，但是我想的就是分离出你的define 的clickhouse代码 然后引入ace的代码 不混在一起

**Comment by yuzd** [comment]
需要你看下ace_clickhouse.js
看怎么分离了
这个小demo是之前写的，当时我是把东西都引入进来了
